name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    
    - name: artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: './dist'
    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "39.102.68.192"
        username: "振锋小哥"
        password: "feng950925"
    
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: "39.102.68.192"
        username: "振锋小哥"
        password: "feng950925"
        source: "./dist"
        target: "/www/webapp/"
